yolo:
  type: "yolov3"
  iou_threshold: 0.5
  score_threshold: 0.005
  max_boxes: 3
  strides: "32,16,8"
  anchors: "10,13 16,30 33,23 30,61 62,45 59,119 116,90 156,198 373,326"
  mask: "6,7,8 3,4,5 0,1,2"
  name_path: "./data/ccpd/ccpd.name"

train:
  label: "ccpd_yolov3_SM_DM_CIoU"
  anno_path: "./data/ccpd/train.txt"
  image_size: "320,352,384,416,448,480,512,544,576,608"

  batch_size: 4
  init_weight_path: "./ckpts/yolov3.h5"
  save_weight_path: "./ckpts"

  loss_type: "CIoU+FL"

  mix_up: false
  cut_mix: false
  mosaic: false
  label_smoothing: false
  normal_method: true

  ignore_threshold: 0.7

test:
  anno_path: "./data/ccpd/vtest.txt"
  image_size: "416"
  batch_size: 1
  init_weight_path: "./ckpts/tmp/ccpd_yolov4_tiny_SM_DM_CIoU/202006131447/mAP-0.5863.h5"