yolo:
  type: "yolov4_tiny"
  iou_threshold: 0.5
  score_threshold: 0.005
  max_boxes: 3
  strides: "32,16"
  anchors: "38,16 57,25 68,53 81,34 96,81 125,57"
  mask: "3,4,5 0,1,2"

train:
  label: "ccpd_yolov4_tiny_SM_DM_CIoU"
  name_path: "./data/ccpd/ccpd.name"
  anno_path: "./data/ccpd/train.txt"
  image_size: "320,352,384,416,448,480,512,544,576,608"

  batch_size: 4
  init_weight_path: "./ckpts/yolov3-tiny.h5"
  save_weight_path: "./ckpts"

  loss_type: "CIoU+FL"

  mix_up: false
  cut_mix: false
  mosaic: false
  label_smoothing: false
  normal_method: true

  ignore_threshold: 0.5

test:
  anno_path: "./data/ccpd/test.txt"
  image_size: "416"
  batch_size: 1
  init_weight_path: ""