yolo:
  type: "yolov3_tiny"
  iou_threshold: 0.45
  score_threshold: 0.5
  max_boxes: 100
  strides: "32,16"
  anchors: "10,14 23,27 37,58 81,82 135,169 344,319"
  mask: "3,4,5 0,1,2"

train:
  label: "yymnist_yolov3_tiny"
  name_path: "./data/yymnist/yymnist.name"
  anno_path: "./data/yymnist/train.txt"
  image_size: "320,352,384,416,448,480,512,544,576,608"

  lr_base: 1e-3
  t_max_epoch: 10
  batch_size: 4
  iter_size: 16
  num_epoch: 101
  init_weight_path: "./ckpts/tmp/voc_yolov3_tiny/202005172320/mAP-0.2568.h5" # "./ckpts/yolov3-tiny.h5"

  sample_rate: 5
  save_weight_path: "./ckpts"

  bbox_loss: "L2"

  mix_up: false
  cut_mix: false
  mosaic: false
  label_smoothing: True

  ignore_threshold: 0.7

test:
  anno_path: "./data/yymnist/test.txt"
  image_size: "416"
  batch_size: 1
  init_weight_path: ""