yolo:
  iou_threshold: 0.45
  score_threshold: 0.3
  max_boxes: 100
  classes: "./disc/coco.name"
  strides: "32,16,8"

  anchors: "10,13 16,30 33,23 30,61 62,45 59,119 116,90 156,198 373,326"
  mask: "6,7,8 3,4,5 0,1,2"

train:
  annot_path: "disc/annotation.txt"
  image_size: "320,352,384,416,448,480,512,544,576,608"

  warmup_epoch: 2
  lr_init: 5e-3
  lr_end: 1e-6
  batch_size: 1
  num_epoch: 40
  init_weights: ""

  ignore_threshold: 0.7

test:
  image_size: "416"
  init_weights: "checkpoints/yolov3/yolov3.h5"









