yolo:
  iou_threshold: 0.45
  score_threshold: 0.3
  max_boxes: 100
  classes: "./data/classes/yymnist.name"
  strides: "32,16"

  anchors: "10,14 23,27 37,58 81,82 135,169 344,319"
  mask: "3,4,5 0,1,2"

train:
  annot_path: "./data/dataset/yymnist_train.txt"
  image_size: "320,352,384,416,448,480,512,544,576,608"
  warmup_epoch: 3
  lr_init: 5e-3
  lr_end: 1e-6
  batch_size: 4
  num_epoch: 50
  init_weight_path: "" #"./checkpoints/tmp/yymnist_yolov3_tiny/202004191515/variables/variables"

  ignore_threshold: 0.7
  save_weight_path: "./checkpoints"

test:
  annot_path: "./data/dataset/yymnist_test.txt"
  image_size: "416"
  batch_size: 4
  init_weight_path: "./checkpoints/tmp/yymnist_yolov3_tiny/202004201728/loss-2.2835.h5"
